### PR TITLE
API.

### PR DESCRIPTION
**Pull request by rebelvg**
This PR adds two API routes.
/streams - basically just shows all currently active streams and their subscribers.
/streams/:app/:stream - shows information about one selected stream.

TODO.
* ~~Protect endpoints with some kind of auth. In this case, I guess only /channels needs protection as it shows all currently active channels and IPs.~~
* ~~Reformat the code to be consistent with the repo code style.~~

To access the key protected api endpoint you have to add a get "apiKey" query to the request with the key.
> http://localhost:8000/api/streams?apiKey=key

How can this be used?
I already made a stats server that collects this data and makes it accessible via website.
https://github.com/rebelvg/stats-node - backend api.
https://github.com/rebelvg/stats-react - frontend.
Live example - http://stats.klpq.men/streams

This is WIP and needs some discussion.
Really want to hear your feedback on this one.

### CODE REVIEW

**Comment by illuspas** [comment]
Very cool ~~
I think this is exactly what is needed.

**Comment by rebelvg** [comment]
Added auth functionality and reformatted the code.
If you have any ideas for what can be added or change, please share!
Otherwise, I think it's ready to be merged.

**Comment by illuspas** [comment]
Why use 'channel' as a keyword, I think using 'stream' as a keyword would be more general ?
And , session.id should be named with 'clientId' .

**Comment by rebelvg** [comment]
Pushed a few fixes. Take a look, please.

**Comment by illuspas** [comment]
I mean, all 'channel' is replaced by 'stream' and 'channels' is replaced by 'streams'.

**Comment by rebelvg** [comment]
Renamed route /channels to /streams.

**Comment by illuspas** [comment]
Well, I will merge the pr, and then do a little modification .

**Pull request merged**
