### PR TITLE
Added checks with promises

### PR DESCRIPTION
**Pull request by dev-steverob**
I have added an alternative to the Event Emit. This is a promise based workflow to allow for promise based request inside the callbacks and then rejecting the stream based on the callbacks return value. I have tried to keep the coding the same style as the current Event Emit. I have added examples to the Readme also.

### CODE REVIEW

**Comment by illuspas** [comment]
Please do not change the current code style.
No spaces between function names and parentheses.

**Comment by dev-steverob** [comment]
Sorry it was my IDE that auto lints I will try to stop it and re submit

**Comment by chrisspiegl** [comment]
Hello @dev-steverob, I think your PR is very interesting, could you reformat this and resubmit?

**Comment by dev-steverob** [comment]
> Hello @dev-steverob, I think your PR is very interesting, could you reformat this and resubmit?

Once I get some time yes I will, I have extended my fork quite a bit more since by adding HLS secure keys to protect front end watching so I will have to split out the code again.

**Comment by mattmatters** [comment]
> > Hello @dev-steverob, I think your PR is very interesting, could you reformat this and resubmit?
> 
> Once I get some time yes I will, I have extended my fork quite a bit more since by adding HLS secure keys to protect front end watching so I will have to split out the code again.

Hey @dev-steverob, this pr has a lot of benefits to us too (asynchronous validation of stream keys). If you are too busy I would be more than happy to clean this pr up for you. :)

**Comment by dev-steverob** [comment]
> > > Hello @dev-steverob, I think your PR is very interesting, could you reformat this and resubmit?
> > 
> > 
> > Once I get some time yes I will, I have extended my fork quite a bit more since by adding HLS secure keys to protect front end watching so I will have to split out the code again.
> 
> Hey @dev-steverob, this pr has a lot of benefits to us too (asynchronous validation of stream keys). If you are too busy I would be more than happy to clean this pr up for you. :)

My folk has moved on a bit since this PR as I needed more functionality, but your welcome to take anything I have done and put it into a PR. You can message me if you need anything from me

**Comment by mattmatters** [comment]
> > > > Hello @dev-steverob, I think your PR is very interesting, could you reformat this and resubmit?
> > > 
> > > 
> > > Once I get some time yes I will, I have extended my fork quite a bit more since by adding HLS secure keys to protect front end watching so I will have to split out the code again.
> > 
> > 
> > Hey @dev-steverob, this pr has a lot of benefits to us too (asynchronous validation of stream keys). If you are too busy I would be more than happy to clean this pr up for you. :)
> 
> My folk has moved on a bit since this PR as I needed more functionality, but your welcome to take anything I have done and put it into a PR. You can message me if you need anything from me

Awesome, will do!

**Comment by lonasozo** [comment]
Hello guys, this would be really interesting, there is no news on that?

**Pull request closed without merging**
